### ISSUE TITLE
Support for Non-homogeneous Poisson processes?

### ISSUE THREAD

**Issue by lwhite1** [dsg-unipr/deus#2]
Does this library support Non-homogeneous Poisson processes? If not, do you know of one that does? 

I want to simulate a production system with arrivals that vary over time, such as a hospital emergency room or restaurant. 

Thank you.

**Comment by ardarico** [comment]
Hi Larry,
currently DEUS does not support non-homogeneous Poisson processes. I noted it, for future releases.

Meanwhile, you can look at this project:  http://simul.iro.umontreal.ca/contactcenters/index.html

**Comment by lwhite1** [comment]
Thank you for the quick response and the pointer.
